### ISSUE TITLE
`additional_data` missing from v2 GetOrganizations model

### ISSUE THREAD

**Issue by vicdelfant** [pipedrive/client-php#169]
It appears that there is no way to get past the first page of results when using the v2 API's `GetOrganizations` model, as the `next_cursor` field is not exposed.

After debugging the API traffic, I found that `additional_data.next_cursor` is returned by the API, but it is missing from the PHP model definition. After manually adding the field definition—borrowing from another response—pagination works as expected.

## Steps to reproduce
1. Call `OrganizationsApi::getOrganizations()` with a large enough dataset to require pagination.
2. Observe that `next_cursor` is not present in the response model.
3. Debugging the API traffic reveals that `next_cursor` is returned, but the SDK does not expose it.

## Expected behavior
The `next_cursor` field should be included in the `GetOrganizations` model, allowing proper pagination.

___

I appreciate the Pipedrive team’s pragmatic approach in using OpenAPI to generate this SDK, as I imagine it helps with consistency and reduces maintenance overhead. However, after encountering both this issue and #168 within just a few hours of working with this SDK, I can’t help but wonder whether this tradeoff has come at the expense of DX for the people actually using this _official_ Pipedrive SDK. 

The developer of the number one library for integrating with Pipedrive [mentioned that he discontinued work on his library](https://github.com/IsraelOrtuno/pipedrive/issues/142) because of Pipedrive's SDK, but it isn't anywhere near as usable as you'd expect.

**Comment by TopHatYami** [comment]
Are there any updates on if/when this will be fixed? 
I'm currently trying to update an integration and have come to a halt due to this being missing.

**Comment by dmitriyeff** [comment]
Hi! Thank you for reporting an issue. Yes, we will try to fix it as soon as possible. When it's done, I will get back to you.

**Comment by dmitriyeff** [comment]
@TopHatYami, issue is fixed in [v8.1.3](https://github.com/pipedrive/client-php/tree/8.1.3)

**Comment by Eizens** [comment]
I used Composer to update the package to 8.1.3 and even reinstalled it. Verified that the version is indeed 8.1.3.
Checked the files there and... it seems that the changes are merged into master branch, but those changes are not present in 8.1.3 tag, thus not working with 8.1.3 version via Composer.

For example take a look at this file. 
https://github.com/pipedrive/client-php/blob/8.1.3/lib/versions/v2/Model/GetOrganizations.php
It is missing following at line 71:
'additional_data' => '\Pipedrive\versions\v2\Model\AdditionalDataWithCursorPagination'

**Comment by dmitriyeff** [comment]
@Eizens, you were right; the wrong commit was tagged. I recreated the tag with the correct changes. Can you verify that it works now? Thank you for spotting the issue.

**Comment by Eizens** [comment]
Yes, now I can confirm that the additional_data appears for getOrganizations and getPersons. Thank you for quick fix!
Although following V2 calls still doesn't have additional_data and so the pagination for those object retrieval is impossible.
getDeals()
getStages()
getPipelines()
getActivities()

**Comment by dmitriyeff** [comment]
I will look at the rest of the methods.

**Comment by dmitriyeff** [comment]
@Eizens, `additional_data` was added [v8.1.4](https://github.com/pipedrive/client-php/tree/8.1.4)
